### ISSUE TITLE
Thumbnails for many categories are blank

### ISSUE THREAD

**Issue by Rex000** [kubaska/twitch-fox#2]
Hi, I have been noticing this issue for some time. There are a lot of categories/games for which thumbnails don't show up in streams. But the said thumbnails show up fine when they are searched via "Browse the top games" tab.

![a0](https://github.com/kubaska/twitch-fox/assets/28770012/9315f3c0-b4ca-4188-89ed-c6a7f6a4a171)
![a1](https://github.com/kubaska/twitch-fox/assets/28770012/8ff6835a-9ede-416e-ba9f-62c8bee826ac)

In the above example, the streamer has set his game as "FIFA 23" but it shows blank despite the fact that the thumbnail for the game is already available. There are many games like that with the same kind of behavior.

**Comment by kubaska** [comment]
Hi Rex, long time no hear! Sorry for very long response time. I have updated the addon to show up to date category image. It will also be available in clip cards along with category name.
