### ISSUE TITLE
Non-local follows not grabbed and other issues

### ISSUE THREAD

**Issue by TernaryC** [kubaska/twitch-fox#3]
I'm not sure if this fork is still being maintained, but on the off-chance it is;
Recently, all of my non-local follows vanished from the extension. I figured that wasn't a significant problem, I could just locally follow all the channels I follow on Twitch.
However, now every currently-live stream is displayed twice. Once for the Twitch follow (which does not appear anywhere else in the extension), and once for the local follow. Of course, if I unfollow locally, this fixes it, but at the expense of none of the other features working.
![image](https://github.com/kubaska/twitch-fox/assets/36998960/69321671-f2b7-4f2c-b204-d678292b0ef0)

**Comment by kubaska** [comment]
Hi,
the issue has been fixed. Twitch changed the API specification and it broke fetching account follows. I actually saw their announcement on this but I missed that it applies to endpoint I use too. On top of that, Github didn't send me a notification that you opened this issue, so sorry for getting so late to this.
To remove the duplicates, unfollow channels that are duplicated. They'll get removed next refresh.
Anyways, new release is up. Thanks for reporting
